const pokemons = [
  {
    id: 1,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
  },
  {
    id: 2,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
    types: ['Feu'],
    created: new Date(),
  },
  {
    id: 3,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
    types: ['Eau'],
    created: new Date(),
  },
  {
    id: 4,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
  },
  {
    id: 5,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
  },
  {
    id: 6,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
  },
  {
    id: 7,
    intitule: 'Dev',
    description: 'vrefververbvbv',
    lieuTravail: 'Toulouse',
    entreprise: 'Airbus',
    created: new Date(),
  },
];

module.exports = pokemons;
